### ISSUE TITLE
More packages

### ISSUE THREAD

**Issue by feliwir** [cpbotha/conan-sfml#1]
Hey, would it be possible to add more packages especially the windows ones? Would be very appreciated, thanks

**Comment by DesktopMan** [comment]
Since there's no pre-built Windows packages I tried to build with with --build=missing. Unfortunately this fails. Log below.

```
D:\dev\dat220\course\examples\sfml_tiled\.conan>conan install .. --build=missing
Requirements
    sfml/2.3.2@cpbotha/stable from conan-transit
Packages
    sfml/2.3.2@cpbotha/stable:a79183e389c623a02563f0681bdb33bc6abbfdf2

sfml/2.3.2@cpbotha/stable: Already installed!
Traceback (most recent call last):
  File "c:\users\cau\appdata\local\programs\python\python36-32\lib\site-packages\conans\client\command.py", line 722, in run
    method(args[0][1:])
  File "c:\users\cau\appdata\local\programs\python\python36-32\lib\site-packages\conans\client\command.py", line 200, in install
    generator=args.generator, no_imports=args.no_imports, filename=args.file)
  File "c:\users\cau\appdata\local\programs\python\python36-32\lib\site-packages\conans\client\conan_api.py", line 57, in wrapper
    return f(*args, **kwargs)
  File "c:\users\cau\appdata\local\programs\python\python36-32\lib\site-packages\conans\client\conan_api.py", line 303, in install
    no_imports=no_imports)
  File "c:\users\cau\appdata\local\programs\python\python36-32\lib\site-packages\conans\client\manager.py", line 282, in install
    installer.install(deps_graph, build_mode, current_path)
  File "c:\users\cau\appdata\local\programs\python\python36-32\lib\site-packages\conans\client\installer.py", line 134, in install
    self._build(nodes_by_level, skip_private_nodes, build_mode)
  File "c:\users\cau\appdata\local\programs\python\python36-32\lib\site-packages\conans\client\installer.py", line 245, in _build
    self._propagate_info(conan_ref, conan_file, flat)
  File "c:\users\cau\appdata\local\programs\python\python36-32\lib\site-packages\conans\client\installer.py", line 256, in _propagate_info
    conan_file.deps_cpp_info.update(n.conanfile.cpp_info, n.conan_ref.name)
  File "c:\users\cau\appdata\local\programs\python\python36-32\lib\site-packages\conans\model\build_info.py", line 213, in update
    super(DepsCppInfo, self).update(dep_cpp_info)
  File "c:\users\cau\appdata\local\programs\python\python36-32\lib\site-packages\conans\model\build_info.py", line 109, in update
    self.libs = merge_lists(self.libs, dep_cpp_info.libs)
  File "c:\users\cau\appdata\local\programs\python\python36-32\lib\site-packages\conans\model\build_info.py", line 102, in merge_lists
    return [s for s in seq1 if s not in seq2] + seq2
TypeError: can only concatenate list (not "map") to list
```
